// src/pages/Index.vue
<template>
  <Layout>
    <Logo class="mx-8 sm:mx-32 mb-4"></Logo>

    <h1 class="w-full text-center text-2xl">Southeast Data Librarian Symposium 2021</h1>
    <h2 class="w-full mt-2 text-center text-xl">Online, the week of October, 11 2021</h2>
    <p>
      The Southeast Data Librarian Symposium (SEDLS) is returning online in 2021! The program will consist of workshops, short presentations, and networking opportunities during the week of October 11, 2021.
    </p>
    <p>
      Check out <a class="link" href="https://se-datalibrarian.github.io/2020/program/">last year's program</a> to view abstracts, posters, and presentation recordings for an idea of content.
    </p>
    <p>
      SEDLS is open to all who wish to attend, including students, data managers, and data scientists. Learn more about SEDLS on the <g-link class="link" to="/about">About Us page</g-link>.
    </p>
    <p>
      This website will be updated with the latest information as planning continues. You can reach out to <a title="Contact us via email" href="mailto:se.datalibrarian@gmail.com">se.datalibrarian@gmail.com</a> with any questions.
    </p>
  </Layout>
</template>

<script>
import Logo from '~/assets/logo-main.svg'

export default {
  components: {
    Logo
  },

  metaInfo: {
    title: 'Home'
  }
}
</script>

<style>
.home-links a {
  margin-right: 1rem;
}
</style>

// pages/index.tsx
import type { NextPage } from 'next'
import Head from 'next/head'
import AnimatedLogo from '../components/logo-animated'
import { symposiumTitle } from '../components/layout'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>{symposiumTitle}</title>
      </Head>
      <AnimatedLogo />
      <h1 className="w-full text-center text-2xl">{symposiumTitle}</h1>
      <p>
        Check out <a className="link" href="https://se-datalibrarian.github.io/2021/program/">last year&#39;s program</a> to view abstracts, posters, and presentation recordings for an idea of content.
      </p>
      <p>
        SEDLS is open to all who wish to attend, including students, data managers, and data scientists. Learn more about SEDLS on the <Link href="/about"><a className="link">About Us page</a></Link>.
      </p>
      <p>
        This website will be updated with the latest information as planning continues. You can reach out to <a title="Contact us via email" href="mailto:se.datalibrarian@gmail.com">se.datalibrarian@gmail.com</a> with any questions.
      </p>
    </>
  )
}

export default Home
